jtype: KafkaToKafka
metas:
  py_modules:
  - kafka2kafka.py
  name: KafkaToKafka
  description: KafkaToKafka executor consumes documents/messages from a topic. Each document
    is converted to a docarray Document adds a random embedding. The docarray Document
    is then written/published to another Kafka topic as json.
  url: http://github.com:jina-ai/executor-kakfa2kafka-processor
  keywords:
  - kafka
  - enrichment
  - message-processing
env:
  BOOTSTRAP_SERVERS: 'localhost:9092'
  CONSUMER_TOPIC: 'input_raw_docs'
  PUBLISH_TOPIC: 'enriched_docs'
  BATCH_SIZE: '5'